import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
// import ReduxProvider from "@/components/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Travelus",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/logo.svg",
    shortcut: "/assets/logo.svg",
    apple: "/assets/logo.svg"
  }
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={`antialiased bg-gray-950 text-gray-400`}>
        {/* <ReduxProvider> */}
          <NavBar />
          {children}
          <Toaster richColors position="top-right"/>
          <Footer />
        {/* </ReduxProvider> */}
      </body>
    </html>
  );
}

